### ISSUE TITLE
Some games give the errror message "Service suspended by owner"

### ISSUE THREAD

**Issue by gamer167** [PurePro4561/PurePro4561.github.io#1]
**Describe the bug**
Some games give the errror message "Service suspended by owner"
**To Reproduce**
In my case I did:
1. Go to 'https://purepro4561.github.io/CC.html'
2. See error

**Expected behavior**
I would think it would let the person play cookie clicker.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WINDOWS 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] ?

**Additional context**
I use this for my own type of purepro but named purefun.

**Comment by PurePro4561** [comment]
Fixed
